### ISSUE TITLE
query clause don't support full text search?

### ISSUE THREAD

**Issue by chenryn** [kiwiz/esquery#1]
seems like only support key:value format to query?

**Comment by kiwiz** [comment]
You should be able to use the `_all` field for this.

**Comment by chenryn** [comment]
So esquery don't want to support the full text string format? Can you tell me the reason or difficulty？thanks very much.

**Comment by kiwiz** [comment]
Moderate difficultly. This is the first request I've seen for this and `_all` allows you to do the same thing. Do you have a good case for implementing this?

**Comment by chenryn** [comment]
Just because users like to write some literal strings like google search,
but not to remember the `field:` format.

2016-10-07 9:22 GMT+08:00 Kai notifications@github.com:

**Comment by kiwiz** [comment]
Implemented via 315e5773e87a8826e3cc0f82f8eac4b9d1be6310.
